"""
Blokus specific configurations
"""
anchor_constraints_dict= {'A': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'B1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'B2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'C1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'C2': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'D1': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'D2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'D3': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'D4': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'E1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-3,
                              },
                        'E2': {'start_col' : 0+3,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'F1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'F2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'F3': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'F4': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'F5': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'F6': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'F7': {'start_col' : 1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'F8': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'G1': {'start_col' : 0+1,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'G2': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'G3': {'start_col' : 0+1,
                               'start_row' : 0+1,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'G4': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'H' : {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'I1': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'I2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'I3': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'I4': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'J1': {'start_col' : 0+4,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'J2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-4,
                              },
                        'K1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-3,
                              },
                        'K2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-3,
                              },
                        'K3': {'start_col' : 0+1,
                               'start_row' : 0+3,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'K4': {'start_col' : 0,
                               'start_row' : 0+3,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'K5': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-3,
                              },
                        'K6': {'start_col' : 0+3,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'K7': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-3,
                               'end_row'   : 13-1,
                              },
                        'K8': {'start_col' : 0+3,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'L1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-3,
                              },
                        'L2': {'start_col' : 0-1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-3,
                              },
                        'L3': {'start_col' : 0+1,
                               'start_row' : 0+3,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'L4': {'start_col' : 0,
                               'start_row' : 0+3,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'L5': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-3,
                               'end_row'   : 13,
                              },
                        'L6': {'start_col' : 0+3,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'L7': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-3,
                               'end_row'   : 13-1,
                              },
                        'L8': {'start_col' : 0+3,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'M1': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'M2': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'M3': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'M4': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'M5': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'M6': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'M7': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'M8': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'N1': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'N2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'N3': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'N4': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'O1': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'O2': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'O3': {'start_col' : 0+1,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'O4': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'O5': {'start_col' : 0+1,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'O6': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'O7': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'O8': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              },
                        'P1': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'P2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'P3': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'P4': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'Q1': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'Q2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-2,
                              },
                        'Q3': {'start_col' : 0+2,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'Q4': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'R1': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'R2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-2,
                              },
                        'R3': {'start_col' : 0+2,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'R4': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'S1': {'start_col' : 0+2,
                               'start_row' : 0,
                               'end_col'   : 13,
                               'end_row'   : 13-2,
                              },
                        'S2': {'start_col' : 0,
                               'start_row' : 0,
                               'end_col'   : 13-2,
                               'end_row'   : 13-2,
                              },
                        'S3': {'start_col' : 0+2,
                               'start_row' : 0+2,
                               'end_col'   : 13,
                               'end_row'   : 13,
                              },
                        'S4': {'start_col' : 0,
                               'start_row' : 0+2,
                               'end_col'   : 13-2,
                               'end_row'   : 13,
                              },
                        'T1': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'T2': {'start_col' : 0+1,
                               'start_row' : 0,
                               'end_col'   : 13-1,
                               'end_row'   : 13-2,
                              },
                        'T3': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'T4': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'T5': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'T6': {'start_col' : 0+1,
                               'start_row' : 0+2,
                               'end_col'   : 13-1,
                               'end_row'   : 13,
                              },
                        'T7': {'start_col' : 0+2,
                               'start_row' : 0+1,
                               'end_col'   : 13,
                               'end_row'   : 13-1,
                              },
                        'T8': {'start_col' : 0,
                               'start_row' : 0+1,
                               'end_col'   : 13-2,
                               'end_row'   : 13-1,
                              },
                        'U':  {'start_col' : 0+1,
                               'start_row' : 0-1,
                               'end_col'   : 13-1,
                               'end_row'   : 13-1,
                              }
                        }

def create_possible_moves_labels(anchor_constraints_dict):
    """
    Creates list of all possible moves in travel blokus (14x14) in two formats.

    With all pieces on a 14x14 grid, 13798 unique moves are possible

    Chess-like move_labels:
    eg: D4c2, piece D in 4th configuration, with anchor point located at column c and row 2.

    grid_labels:
    eg: D4-170, piece D in 4th configuration, with anchor point located at 170 in array

    See moves_diagram.png for anchor points and piece configurations.
    piece configurations: [A, B1-B2, C1-C2, D1-D4, E1-E2, F1-F8, G1-G8, H, I1-I4, J1-J2, K1-K8, L1-L8,
                       M1-M8, N1-N4, O1-O8, P1-P4, Q1,Q4, R1-R4, S1-S4, T1-T8, U]

    move_labels:
       _ _ _ ... _ _ _
    14|               |
    13|               |
    12|               |
    ...               ...
     3|               |
     2|               |
     1|_ _ _     _ _ _|
       a b c ... l m n

     grid_labels:
     ___ ___ ___       ___ ___ ___
    |0  |1  |2  | ... |11 |12 |13 |
    |14 |15 |16 | ... |25 |26 |27 |
    |28 |29 |30 | ... |39 |40 |41 |
    ...  ... ...  ...  ... ... ...
    |154|155|156| ... |165|166|167|
    |168|169|170| ... |179|180|181|
    |182|183|184| ... |193|194|195|
    -------------------------------

    Args:
        anchor_constraints_dict: dict to reference unique board constraints of pieces by configuration and anchor point location
    Returns:
        move_labels, grid_labels : lists of all possible moves as strings in two formats

    """
    move_labels = []
    grid_labels =[]
    letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']
    numbers = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14']

    def convert_move_idx_to_grid(n_idx, l_idx):
        return abs(n_idx-13)*14 + l_idx

    for key, constraints in anchor_constraints_dict.items():
        print("\n {} \n".format(key))
        for n in range(constraints['start_row'], constraints['end_row']+1):
            for l in range(constraints['start_col'], constraints['end_col']+1):
                move_labels.append(key + letters[l] + numbers[n])
                grid_labels.append("{}-{}".format(key, convert_move_idx_to_grid(n,l)))

    return move_labels, grid_labels


class BlokusConfig:
    """
    Blokus specific config info describing how to run the application

    Attributes:
        action: idx to action in self.actionSpace?


    Attributes (best guess so far):
        :ivar list(str) labels: labels to use for representing the game using UCI
        :ivar int n_lables: number of labels
    """
    move_labels, grid_labels = create_possible_moves_labels()
    n_possible_moves = len(move_labels)
    all_shape_configurations = ['A', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2', 'D3', 'D4', 'E1', 'E2',
                                 'F1', 'F2', 'F3', 'F4', 'F5', 'F6','F7', 'F8', 'G1', 'G2', 'G3',
                                 'G4', 'H', 'I1', 'I2', 'I3', 'I4', 'J1', 'J2', 'K1', 'K2', 'K3',
                                 'K4', 'K5', 'K6', 'K7', 'K8', 'L1', 'L2', 'L3', 'L4', 'L5', 'L6',
                                 'L7', 'L8', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'N1',
                                 'N2', 'N3', 'N4', 'O1', 'O2', 'O3', 'O4', 'O5', 'O6', 'O7', 'O8',
                                 'P1', 'P2', 'P3', 'P4', 'Q1', 'Q2', 'Q3', 'Q4', 'R1', 'R2', 'R3',
                                 'R4', 'S1', 'S2', 'S3', 'S4', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6',
                                 'T7', 'T8', 'U'
                                 ]
    all_shapes = ['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
                  'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U']

    def __init__(self):
        self.move_labels = move_labels
        self.grid_labels = grid_labels
        self.n_possible_moves = n_possible_moves
        self.all_shape_configurations = all_shape_configurations
        self.all_shapes = all_shapes
